name: good-day
channels:
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.0.5
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - comm=0.2.1
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - executing=0.8.3
  - expat=2.5.0
  - fonttools=4.25.0
  - freetype=2.12.1
  - intel-openmp=2023.1.0
  - ipykernel=6.28.0
  - ipython=8.20.0
  - jedi=0.18.1
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.13
  - packaging=23.1
  - pandas=2.2.1
  - parso=0.8.3
  - pexpect=4.8.0
  - pillow=10.2.0
  - pip=23.3.1
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pyparsing=3.0.9
  - python=3.12.2
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - pyzmq=25.1.2
  - readline=8.2
  - scikit-learn=1.3.0
  - scipy=1.11.3
  - seaborn=0.12.2
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - traitlets=5.7.1
  - tzdata=2024a
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.6
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - attrs==23.2.0
    - babel==2.14.0
    - commonmark==0.9.1
    - fastjsonschema==2.19.1
    - great-tables==0.4.0
    - htmltools==0.5.1
    - importlib-metadata==7.0.2
    - jsonschema==4.21.1
    - jsonschema-specifications==2023.12.1
    - mizani==0.11.0
    - nbclient==0.10.0
    - nbformat==5.10.3
    - pandas-flavor==0.6.0
    - patsy==0.5.6
    - pingouin==0.5.4
    - plotnine==0.13.1
    - pyyaml==6.0.1
    - referencing==0.34.0
    - rpds-py==0.18.0
    - statsmodels==0.14.1
    - tabulate==0.9.0
    - typing-extensions==4.10.0
    - webcolors==1.13
    - xarray==2024.2.0
    - zipp==3.18.1
